In [9]:
import json
import requests
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [33]:
def process_json_file(file_address, output_csv_path):
    try:
        # Create an empty dataframe to store the result
        result_df = pd.DataFrame()

        with open(file_address, 'r') as file:
            data = json.load(file)

            # Check if the data is a list of JSON objects
            if isinstance(data, list):
                for idx, json_object in enumerate(data, start=1):
                    scheme_code = json_object.get('schemeCode')

                    # Check if 'schemeCode' is present in the JSON object
                    if scheme_code is not None:
                        api_url = f'https://api.mfapi.in/mf/{scheme_code}'
                        response = requests.get(api_url)

                        if response.status_code == 200:
                            mf_data = response.json()['data']

                            # Create a dataframe for each API response
                            df = pd.DataFrame(mf_data, columns=['date', 'nav'])
                            col_name = json_object.get('schemeName')
                            df = df.rename(columns={'nav': col_name})

                            # Merge with the result dataframe based on the "date" column
                            if result_df.empty:
                                result_df = df
                            else:
                                result_df = pd.merge(result_df, df, on='date', how='outer')
                        else:
                            print(f'Failed to fetch data for scheme code {scheme_code}. Status code: {response.status_code}')
                    else:
                        print(f'Missing schemeCode in JSON object {idx}.')

                # Convert "date" column to datetime format
                result_df['date'] = pd.to_datetime(result_df['date'], format='%d-%m-%Y')

                # Sort the merged dataframe based on the "date" column
                result_df = result_df.sort_values(by='date')

                # Save the dataframe to a CSV file without index
                result_df.to_csv(output_csv_path, index=False)

                print(f'Merged, Converted, and Sorted DataFrame saved to: {output_csv_path}')
            else:
                print("Invalid JSON format. The file should contain a list of JSON objects.")

    except FileNotFoundError:
        print(f"File not found: {file_address}")
    except json.JSONDecodeError as e:
        print(f"Error decoding JSON in file {file_address}: {e}")
    return result_df

In [35]:
# Example usage:
file_address = 'output/elss_mf.json'
output_csv_path = 'output/csv/elss_mf.csv'
process_json_file(file_address, output_csv_path)

Merged, Converted, and Sorted DataFrame saved to: output/csv/elss_mf.csv

,date,Quantum ELSS Tax Saver Fund - Direct Plan Growth Option,BANDHAN ELSS Tax Saver Fund - Direct Plan - Growth,IDFC Tax Advantage (ELSS) Fund-Direct Plan-Growth
3721,2008-12-31,9.98400,NaN,NaN
0,2009-01-01,10.11100,NaN,NaN
118,2009-01-02,10.15500,NaN,NaN
480,2009-01-05,10.33700,NaN,NaN
603,2009-01-06,10.37100,NaN,NaN
...,...,...,...,...
2347,2024-02-20,110.17000,154.83400,154.83400
2473,2024-02-21,109.82000,153.94900,153.94900
2598,2024-02-22,110.47000,155.17600,155.17600
2725,2024-02-23,110.51000,155.44700,155.44700
3076,2024-02-26,110.26000,154.75200,154.75200

In [32]:
data.tail()

,date,Quantum ELSS Tax Saver Fund - Direct Plan Growth Option,BANDHAN ELSS Tax Saver Fund - Direct Plan - Growth,IDFC Tax Advantage (ELSS) Fund-Direct Plan-Growth
2347,2024-02-20,110.17000,154.83400,154.83400
2473,2024-02-21,109.82000,153.94900,153.94900
2598,2024-02-22,110.47000,155.17600,155.17600
2725,2024-02-23,110.51000,155.44700,155.44700
3076,2024-02-26,110.26000,154.75200,154.75200

In [1]:
from toolkit import function

In [4]:
file_address = 'output/elss_mf.json'
output_csv_path = 'output/csv/elss_mf.csv'
data = function.json_csv_creator(file_address, output_csv_path)

Merged, Converted, and Sorted DataFrame saved to: output/csv/elss_mf.csv

In [5]:
data.head()

           date  ... Zerodha ELSS Tax Saver Nifty LargeMidcap 250 Index Fund - Direct Plan - Growth option
3739 2008-12-31  ...                                                NaN
0    2009-01-01  ...                                                NaN
118  2009-01-02  ...                                                NaN
483  2009-01-05  ...                                                NaN
607  2009-01-06  ...                                                NaN

[5 rows x 54 columns]